# TCL File Generated by Component Editor 15.1
# Mon Dec 28 18:45:26 JST 2015
# DO NOT MODIFY


# 
# uart_to_avalon_bridge "uart_to_avalon_bridge" v0.9
# S.OSAFUNE / J-7SYSTEM WORKS 2015.12.28.18:45:26
# PERIDOT UART to Avalon-MM Bridge
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module uart_to_avalon_bridge
# 
set_module_property DESCRIPTION "PERIDOT UART to Avalon-MM Bridge"
set_module_property NAME uart_to_avalon_bridge
set_module_property VERSION 0.9
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "S.OSAFUNE / J-7SYSTEM WORKS"
set_module_property DISPLAY_NAME uart_to_avalon_bridge
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL uart_to_avalon_bridge
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file altera_avalon_packets_to_master.v VERILOG PATH altera_avalon_packets_to_master.v
add_fileset_file altera_avalon_st_bytes_to_packets.v VERILOG PATH altera_avalon_st_bytes_to_packets.v
add_fileset_file altera_avalon_st_packets_to_bytes.v VERILOG PATH altera_avalon_st_packets_to_bytes.v
add_fileset_file peridot_bytes_to_uart.v VERILOG PATH peridot_bytes_to_uart.v
add_fileset_file peridot_dummy_conf.v VERILOG PATH peridot_dummy_conf.v
add_fileset_file peridot_board_eeprom.v VERILOG PATH peridot_board_eeprom.v
add_fileset_file peridot_i2c_serial.v VERILOG PATH peridot_i2c_serial.v
add_fileset_file peridot_phy_rxd.v VERILOG PATH peridot_phy_rxd.v
add_fileset_file peridot_phy_txd.v VERILOG PATH peridot_phy_txd.v
add_fileset_file peridot_uart_infifo.v VERILOG PATH peridot_uart_infifo.v
add_fileset_file uart_to_avalon_bridge.v VERILOG PATH uart_to_avalon_bridge.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter CLOCK_FREQUENCY INTEGER 0
set_parameter_property CLOCK_FREQUENCY DISPLAY_NAME "Clock frequency"
set_parameter_property CLOCK_FREQUENCY UNITS Hertz
set_parameter_property CLOCK_FREQUENCY SYSTEM_INFO {CLOCK_RATE clock}
set_parameter_property CLOCK_FREQUENCY HDL_PARAMETER true
set_parameter_property CLOCK_FREQUENCY ENABLED false
#set_parameter_property CLOCK_FREQUENCY VISIBLE false

add_parameter UART_BAUDRATE INTEGER 115200
set_parameter_property UART_BAUDRATE DISPLAY_NAME "Baud rate (bps)"
set_parameter_property UART_BAUDRATE ALLOWED_RANGES {57600 115200 230400}
set_parameter_property UART_BAUDRATE HDL_PARAMETER true

add_parameter BOARD_SERIAL STD_LOGIC_VECTOR 0xFFFFFFFFFFFF4646464646464646464646464646464633395832374A0257374A
set_parameter_property BOARD_SERIAL DISPLAY_NAME "Board serial ID"
set_parameter_property BOARD_SERIAL WIDTH 256
set_parameter_property BOARD_SERIAL HDL_PARAMETER true
set_parameter_property BOARD_SERIAL ENABLED false
set_parameter_property BOARD_SERIAL VISIBLE false


# 
# display items
# 
add_display_item "Information" CLOCKFREQ text "Maximum frequency of clock signal is 100MHz."


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rsi_reset reset Input 1


# 
# connection point m1
# 
add_interface m1 avalon start
set_interface_property m1 addressUnits SYMBOLS
set_interface_property m1 associatedClock clock
set_interface_property m1 associatedReset reset
set_interface_property m1 bitsPerSymbol 8
set_interface_property m1 burstOnBurstBoundariesOnly false
set_interface_property m1 burstcountUnits WORDS
set_interface_property m1 doStreamReads false
set_interface_property m1 doStreamWrites false
set_interface_property m1 holdTime 0
set_interface_property m1 linewrapBursts false
set_interface_property m1 maximumPendingReadTransactions 0
set_interface_property m1 maximumPendingWriteTransactions 0
set_interface_property m1 readLatency 0
set_interface_property m1 readWaitTime 1
set_interface_property m1 setupTime 0
set_interface_property m1 timingUnits Cycles
set_interface_property m1 writeWaitTime 0
set_interface_property m1 ENABLED true
set_interface_property m1 EXPORT_OF ""
set_interface_property m1 PORT_NAME_MAP ""
set_interface_property m1 CMSIS_SVD_VARIABLES ""
set_interface_property m1 SVD_ADDRESS_GROUP ""

add_interface_port m1 avm_m1_address address Output 32
add_interface_port m1 avm_m1_readdata readdata Input 32
add_interface_port m1 avm_m1_read read Output 1
add_interface_port m1 avm_m1_write write Output 1
add_interface_port m1 avm_m1_byteenable byteenable Output 4
add_interface_port m1 avm_m1_writedata writedata Output 32
add_interface_port m1 avm_m1_waitrequest waitrequest Input 1
add_interface_port m1 avm_m1_readdatavalid readdatavalid Input 1


# 
# connection point conduit
# 
add_interface export conduit end
set_interface_property export associatedClock clock
set_interface_property export associatedReset reset
set_interface_property export ENABLED true
set_interface_property export EXPORT_OF ""
set_interface_property export PORT_NAME_MAP ""
set_interface_property export CMSIS_SVD_VARIABLES ""
set_interface_property export SVD_ADDRESS_GROUP ""

add_interface_port export coe_rxd rxd Input 1
add_interface_port export coe_txd txd Output 1
